name: Install testing tools
runs:
  using: composite
  steps:
    # smoelius: https://docs.solana.com/cli/install-solana-cli-tools
    - name: Install Agave
      if: ${{ runner.os != 'Windows' }}
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.18/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Install Anchor prerequisites on Ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt install libudev-dev
      shell: bash

    # smoelius: https://www.anchor-lang.com/docs/installation
    - name: Install Anchor
      if: ${{ runner.os != 'Windows' }}
      run: |
        mkdir -p ~/.config/solana
        cp backends/src/anchor/rfc8032_test_vector.json ~/.config/solana/id.json
        if [[ "$(anchor --version)" != 'anchor-cli 0.31.1' ]]; then
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli --force
        fi
      shell: bash

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.0.0

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "^1.22.2"
        cache: false

    # smoelius: The Chainlink Foundry test requires `node` and `pnpm`.
    - name: Install Node.js
      uses: actions/setup-node@v4

    - name: Install Yarn
      if: ${{ runner.os == 'Windows' }}
      run: npm install --global yarn
      shell: bash

    - name: Install pnpm
      run: npm install --global pnpm
      shell: bash

    - name: Install Setuptools
      if: ${{ runner.os == 'macOS' }}
      run: pip install setuptools
      shell: bash
