[package]
name = "necessist-core"
version = "0.1.0-beta.7"
edition = "2021"

description = "necessist-core"

authors = ["Samuel Moelius <sam@moeli.us>"]
license = "AGPL-3.0"
repository = "https://github.com/trailofbits/necessist"

[[test]]
name = "ci"
path = "tests/ci.rs"
required-features = ["ci"]

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
atty = "0.2"
bitflags = "2.0"
clap = { version = "4.1", features = ["cargo", "derive"], optional = true }
ctrlc = "3.2"
diesel = { version = "2.0", features = ["sqlite"] }
git2 = "0.16"
heck = "0.4"
indicatif = "0.17"
lazy_static = "1.4"
log = "0.4"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
regex = "1.7"
remain = "0.2"
serde = { version = "1.0", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
subprocess = "0.2"
tempfile = "3.4"
toml = "0.7"

[dev-dependencies]
assert_cmd = "2.0"
ctor = "0.1"
curl = "0.4"
fs_extra = "1.3"
predicates = "3.0"
trycmd = "0.14"

[build-dependencies]
cargo_metadata = "0.15"
curl = "0.4"
heck = "0.4"
syn = "2.0"

[features]
default = []
ci = []
dogfood = []
