[package]
name = "necessist-core"
version = "0.1.0-beta.6"
edition = "2021"

description = "necessist-core"

authors = ["Samuel Moelius <sam@moeli.us>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/necessist"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
atty = "0.2"
bitflags = "1.3"
clap = { version = "4.0", features = ["cargo", "derive"], optional = true }
ctrlc = "3.2"
diesel = { version = "2.0", features = ["sqlite"] }
git2 = "0.15"
heck = "0.4"
if_chain = "1.0"
indicatif = "0.17"
lazy_static = "1.4"
log = "0.4"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
regex = "1.7"
remain = "0.2"
serde = "1.0"
strum = "0.24"
strum_macros = "0.24"
subprocess = "0.2"
tempfile = "3.3"
toml = "0.5"
walkdir = "2.3"

# Hardhat TS
swc_core = { version = "0.51", features = ["common", "ecma_ast", "ecma_parser", "ecma_visit"] }

# Rust
cargo_metadata = "0.15"
syn = { version = "1.0", features = ["extra-traits", "full", "visit"] }

[dev-dependencies]
assert_cmd = "2.0"
curl = "0.4"
fs_extra = "1.2"
predicates = "2.1"
trycmd = "0.14"

[features]
default = []
ci = []
ci_nightly = []
