name: Update end-to-end tests

on:
  schedule:
    - cron: "0 3 * * thu"
  workflow_dispatch:

concurrency:
  group: update-end-to-end-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Update end-to-end tests
        run: |
          scripts/update_end_to_end_tests.sh
          scripts/update_go_end_to_end_tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/ci
        env:
          TESTS: end_to_end_0 end_to_end_1
          BLESS: "1"

      - name: Require that a snapshot changed
        id: snapshot
        run: |
          set +e
          git diff --quiet -- '*.stdout'
          status=$?
          set -e
          if [ "$status" -eq 1 ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          elif [ "$status" -ne 0 ]; then
            exit "$status"
          fi

      # smoelius: After blessing the new output, verify that all tests pass. Note that this only
      # runs on `ubuntu-latest`, so it is not as thorough as running the CI workflow.
      - uses: ./.github/actions/ci
        if: steps.snapshot.outputs.changed == 'true'
        env:
          TESTS: end_to_end_0 end_to_end_1 trycmd other ci

      - name: Create pull request
        if: steps.snapshot.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          title: "Update end-to-end tests"
          commit-message: "Update end-to-end tests"
          branch-suffix: random
